name: Auto Delete Old Backups
on:
  schedule:
    - cron: "0 * * * *"  # 每小时整点运行一次（UTC时间）
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install huggingface-hub
          pip install pytz tenacity  # 新增依赖

      - name: Run Delete Script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python delete_old_backups.py
          # 将日志文件作为产物保存（调试用）
          echo "=== 删除日志 ==="
          cat delete_backups.log
          
      - name: Upload Log File
        uses: actions/upload-artifact@v3
        with:
          name: backup-cleanup-log
          path: delete_backups.log  # 上传日志文件作为产物
